In [1]:
import pandas as pd 
import json
import joblib

In [2]:
import os
os.getcwd()
os.chdir('/Users/campbelltaylor/College_Football_Gambling_Model/')

In [3]:
### Load Week Update Data
data = pd.read_csv('Data/CFB_Pred_Week_14.csv')
data

,away_team,home_team,game_id,season,week,neutral_site,conference_game,spread,home_favored,home_covered,...,away_total_receiving_ppa,away_total_rushing_ppa,away_percent_ppa,away_percent_passing_ppa,away_percent_receiving_ppa,away_percent_rushing_ppa,away_usage,away_passing_usage,away_receiving_usage,away_rushing_usage
0,Air Force,Colorado State,401760421,NaN,14,NaN,NaN,2.666667,0,NaN,...,78.1,51.3,0.630,0.226,0.818,0.501,0.556,0.075,0.828,0.640
1,Alabama,Auburn,401752784,NaN,14,NaN,NaN,6.000000,0,NaN,...,118.8,22.3,0.433,0.394,0.571,0.208,0.395,0.098,0.647,0.482
2,Arizona,Arizona State,401756961,NaN,14,NaN,NaN,1.333333,0,NaN,...,98.3,13.5,0.561,1.044,0.379,1.089,0.675,0.985,0.440,0.410
3,Arkansas State,App State,401761661,NaN,14,NaN,NaN,2.666667,1,NaN,...,146.2,25.0,0.586,0.896,0.534,0.354,0.701,0.945,0.443,0.596
4,Army,UTSA,401762441,NaN,14,NaN,NaN,7.500000,1,NaN,...,29.7,58.2,0.252,0.106,0.354,0.245,0.297,0.151,0.451,0.305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,Wake Forest,Duke,401754610,NaN,14,NaN,NaN,1.500000,1,NaN,...,62.0,35.5,0.262,0.000,0.268,0.575,0.359,0.000,0.245,0.834
62,Western Kentucky,Jacksonville State,401757312,NaN,14,NaN,NaN,2.833333,0,NaN,...,133.1,-1.3,0.332,0.175,0.446,-0.066,0.267,0.170,0.415,0.253
63,Western Michigan,Eastern Michigan,401762869,NaN,14,NaN,NaN,10.166667,0,NaN,...,195.0,81.3,0.999,1.000,1.000,1.000,1.000,1.000,1.000,1.000
64,Wisconsin,Minnesota,401752918,NaN,14,NaN,NaN,1.333333,1,NaN,...,107.3,20.4,0.402,0.061,0.564,0.324,0.248,0.003,0.516,0.333
65,Wyoming,Hawai'i,401760424,NaN,14,NaN,NaN,7.833333,1,NaN,...,158.7,3.1,0.774,1.000,0.801,0.147,0.876,1.000,0.789,0.804

In [4]:
with open("Model Information/selected_features_best_model_20250915.json", "r") as f:
    pred_features = json.load(f)
pred_features

['home_prev_week_Offense_First_Down_Success_Rate',
 'away_possession_time_avg3',
 'away_interception_tds_avg_all',
 'home_passes_deflected_allowed_avg_all',
 'away_prev_week_punt_returns_allowed',
 'away_interception_yards_allowed_avg3',
 'away_fourth_down_attempts_allowed_avg_all',
 'away_total_plays_against_avg3',
 'home_Defense_First_Down_Pass_Success_Rate_avg3',
 'away_Offense_First_Down_Run_Success_Rate_avg_all',
 'away_prev_week_total_yards_allowed',
 'away_penalty_yard_margin_avg3',
 'away_rushing_attempts_allowed_avg3',
 'home_Offense_First_Down_Success_avg3',
 'away_prev_week_point_differential',
 'away_kick_return_yards_avg3',
 'home_net_passing_yards_avg3',
 'away_prev_week_Defense_Total_Pass_Plays',
 'away_tackles_avg_all',
 'away_prev_week_interception_yards',
 'away_prev_week_Offense_Scoring_Drive_Percentage',
 'away_Defense_Total_Run_Plays_avg3',
 'away_prev_week_Defense_first_down_pass_rate',
 'away_sacks_avg_all',
 'home_prev_week_total_plays_against',
 'away_rushing_usage',
 'home_prev_week_Total_Defense_Pass_Explosive_Rate',
 'away_points_avg_all',
 'away_prev_week_rush_percentage_against',
 'away_prev_week_points',
 'away_kicking_points_allowed_avg_all',
 'away_prev_week_Offense_Run_Success_Rate',
 'away_Defense_first_down_pass_rate_avg3',
 'home_prev_week_penalty_yard_margin',
 'home_prev_week_yards_per_rush_attempt_allowed',
 'home_prev_week_net_passing_yards',
 'away_kick_returns_allowed_avg_all',
 'home_prev_week_Offense_Run_Success_Rate',
 'away_passes_deflected_allowed_avg3',
 'home_Defense_First_Down_Run_Success_avg_all',
 'home_prev_week_fourth_down_attempts_allowed',
 'home_total_yards_allowed_avg_all',
 'away_Scaled_Talent',
 'away_prev_week_sack_percentage',
 'away_rushing_yards_allowed_avg3',
 'spread',
 'away_punt_returns_allowed_avg3',
 'home_Offense_EPA_per_Play_avg_all',
 'home_Defense_First_Down_Run_Success_Rate_avg3',
 'away_tackles_for_loss_allowed_avg3',
 'away_Total_Offense_EPA_Run_avg3',
 'home_sacks_allowed_avg3']

In [5]:
pred_data = data[pred_features]
pred_data

,home_prev_week_Offense_First_Down_Success_Rate,away_possession_time_avg3,away_interception_tds_avg_all,home_passes_deflected_allowed_avg_all,away_prev_week_punt_returns_allowed,away_interception_yards_allowed_avg3,away_fourth_down_attempts_allowed_avg_all,away_total_plays_against_avg3,home_Defense_First_Down_Pass_Success_Rate_avg3,away_Offense_First_Down_Run_Success_Rate_avg_all,...,away_Scaled_Talent,away_prev_week_sack_percentage,away_rushing_yards_allowed_avg3,spread,away_punt_returns_allowed_avg3,home_Offense_EPA_per_Play_avg_all,home_Defense_First_Down_Run_Success_Rate_avg3,away_tackles_for_loss_allowed_avg3,away_Total_Offense_EPA_Run_avg3,home_sacks_allowed_avg3
0,0.387097,35.111111,0.0,3.8,1,0.000000,1.200000,55.666667,0.330087,0.464451,...,0.000000,0.000000,159.666667,2.666667,0.333333,-0.000141,0.443320,3.333333,0.479818,2.666667
1,0.523810,30.005556,0.2,3.2,1,29.000000,1.600000,59.666667,0.466667,0.421545,...,2.202372,0.086957,81.333333,6.000000,1.000000,0.023706,0.444989,5.000000,-4.187898,4.000000
2,0.370370,29.011111,0.1,4.8,1,0.000000,2.500000,68.000000,0.513228,0.398959,...,-0.005126,0.035714,163.000000,1.333333,1.000000,0.055934,0.423864,6.333333,2.445212,1.666667
3,0.190476,28.983333,0.1,5.9,0,15.666667,1.300000,70.333333,0.581871,0.381575,...,-0.394745,0.085714,107.000000,2.666667,0.333333,0.002145,0.490530,5.666667,-2.231876,2.000000
4,0.742857,34.177778,0.0,3.3,0,0.000000,2.777778,57.333333,0.495425,0.379992,...,-4.059232,0.000000,142.000000,7.500000,1.000000,0.126840,0.541667,2.000000,2.444065,2.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,0.300000,32.022222,0.0,3.0,1,11.666667,2.000000,60.666667,0.519409,0.364826,...,-0.163039,0.054054,123.000000,1.500000,1.333333,0.204281,0.484127,4.333333,4.875777,2.666667
62,0.480000,32.966667,0.1,2.5,0,28.333333,2.200000,72.000000,0.413960,0.453955,...,-0.587844,0.047619,109.000000,2.833333,1.333333,0.097631,0.300654,6.333333,-3.571162,0.666667
63,0.428571,31.427778,0.1,3.2,1,0.000000,1.100000,55.666667,0.611111,0.410656,...,-0.762220,0.105263,140.000000,10.166667,0.666667,0.085934,0.377778,4.666667,1.088792,1.000000
64,0.347826,27.483333,0.0,4.0,2,0.000000,1.200000,64.666667,0.508059,0.329956,...,0.715040,0.200000,134.333333,1.333333,2.666667,-0.013273,0.502315,5.666667,-4.283253,2.333333
65,0.466667,29.094444,0.1,3.3,2,15.000000,1.600000,65.666667,0.269360,0.414052,...,-1.052869,0.037037,168.666667,7.833333,2.333333,0.039204,0.477498,6.000000,-1.134872,1.000000

In [6]:
### Load Model
import xgboost
model = joblib.load("Model Information/best_xgb_model_20250915.pkl")

In [7]:
import numpy as np
X_pred = pred_data[model.get_booster().feature_names]

cover_pred = model.predict(X_pred)
cover_prob = model.predict_proba(X_pred)[:, 1]

data['Cover_Prob'] = cover_prob
data['Cover_Prediction'] = np.where(cover_prob >= 0.6, 1, 0)
data

,away_team,home_team,game_id,season,week,neutral_site,conference_game,spread,home_favored,home_covered,...,away_percent_ppa,away_percent_passing_ppa,away_percent_receiving_ppa,away_percent_rushing_ppa,away_usage,away_passing_usage,away_receiving_usage,away_rushing_usage,Cover_Prob,Cover_Prediction
0,Air Force,Colorado State,401760421,NaN,14,NaN,NaN,2.666667,0,NaN,...,0.630,0.226,0.818,0.501,0.556,0.075,0.828,0.640,0.382206,0
1,Alabama,Auburn,401752784,NaN,14,NaN,NaN,6.000000,0,NaN,...,0.433,0.394,0.571,0.208,0.395,0.098,0.647,0.482,0.695786,1
2,Arizona,Arizona State,401756961,NaN,14,NaN,NaN,1.333333,0,NaN,...,0.561,1.044,0.379,1.089,0.675,0.985,0.440,0.410,0.456945,0
3,Arkansas State,App State,401761661,NaN,14,NaN,NaN,2.666667,1,NaN,...,0.586,0.896,0.534,0.354,0.701,0.945,0.443,0.596,0.510454,0
4,Army,UTSA,401762441,NaN,14,NaN,NaN,7.500000,1,NaN,...,0.252,0.106,0.354,0.245,0.297,0.151,0.451,0.305,0.533338,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,Wake Forest,Duke,401754610,NaN,14,NaN,NaN,1.500000,1,NaN,...,0.262,0.000,0.268,0.575,0.359,0.000,0.245,0.834,0.386946,0
62,Western Kentucky,Jacksonville State,401757312,NaN,14,NaN,NaN,2.833333,0,NaN,...,0.332,0.175,0.446,-0.066,0.267,0.170,0.415,0.253,0.411852,0
63,Western Michigan,Eastern Michigan,401762869,NaN,14,NaN,NaN,10.166667,0,NaN,...,0.999,1.000,1.000,1.000,1.000,1.000,1.000,1.000,0.515212,0
64,Wisconsin,Minnesota,401752918,NaN,14,NaN,NaN,1.333333,1,NaN,...,0.402,0.061,0.564,0.324,0.248,0.003,0.516,0.333,0.384827,0
65,Wyoming,Hawai'i,401760424,NaN,14,NaN,NaN,7.833333,1,NaN,...,0.774,1.000,0.801,0.147,0.876,1.000,0.789,0.804,0.649709,1

In [8]:
predictions = data[['home_team', 'away_team','spread','home_favored' ,'Cover_Prediction', 'Cover_Prob']].sort_values(by='Cover_Prob', ascending=False)

In [9]:
predictions[predictions['Cover_Prediction'] == 1].reset_index(drop=True).rename(columns={'Cover_Prob':'Home Team Cover Probability', 'Cover_Prediction':'Home Team Cover Prediction'})

,home_team,away_team,spread,home_favored,Home Team Cover Prediction,Home Team Cover Probability
0,Illinois,Northwestern,6.833333,1,1,0.887026
1,USC,UCLA,22.166667,1,1,0.778444
2,Southern Miss,Troy,6.500000,1,1,0.758019
3,Arkansas,Missouri,2.666667,0,1,0.738732
4,Liberty,Kennesaw State,2.333333,0,1,0.715681
5,TCU,Cincinnati,3.833333,1,1,0.714033
6,Kansas State,Colorado,16.666667,1,1,0.697827
7,Auburn,Alabama,6.000000,0,1,0.695786
8,Texas,Texas A&M,2.500000,1,1,0.695216
9,Purdue,Indiana,28.500000,0,1,0.691091
10,Baylor,Houston,2.500000,1,1,0.674443
11,Delaware,UTEP,4.333333,1,1,0.663758
12,California,SMU,13.500000,0,1,0.659294
13,Hawai'i,Wyoming,7.833333,1,1,0.649709
14,West Virginia,Texas Tech,24.333333,0,1,0.647051
15,Old Dominion,Georgia State,27.000000,1,1,0.646207
16,Kansas,Utah,11.666667,0,1,0.640913
17,Washington,Oregon,6.666667,0,1,0.636592
18,Stanford,Notre Dame,32.500000,0,1,0.622408
19,Mississippi State,Ole Miss,7.166667,0,1,0.618325
20,Michigan State,Maryland,3.833333,1,1,0.607757
21,Memphis,Navy,5.333333,1,1,0.605760

In [11]:
predictions

,home_team,away_team,spread,home_favored,Cover_Prediction,Cover_Prob
35,Illinois,Northwestern,6.833333,1,1,0.887026
54,USC,UCLA,22.166667,1,1,0.778444
51,Southern Miss,Troy,6.500000,1,1,0.758019
32,Arkansas,Missouri,2.666667,0,1,0.738732
24,Liberty,Kennesaw State,2.333333,0,1,0.715681
...,...,...,...,...,...,...
55,Louisiana,UL Monroe,9.500000,1,0,0.292853
41,Washington State,Oregon State,13.500000,1,0,0.290883
28,Missouri State,Louisiana Tech,2.500000,1,0,0.260504
52,Tulsa,UAB,8.333333,1,0,0.238549
42,Rutgers,Penn State,13.333333,0,0,0.218279